### PR TITLE
Include DLL's

### PR DESCRIPTION
**Pull request by Xanderplayz16**

### CODE REVIEW

**Comment by TheRealMichaelWang** [comment]
In addition please refer to [the updated stdlib default foreign functions](https://github.com/TheRealMichaelWang/cish/blob/main/src/stdlibf.c) for any potential changes.

I also wanted to point out that dllimport is done through foreign[19], since a couple other foreign functions have been added to stdlib default foreign functions.

**Comment by Xanderplayz16** [comment]
Just fixed the code.

**Review by TheRealMichaelWang — APPROVED** [review]
Looking great!

**Review by TheRealMichaelWang — CHANGES_REQUESTED** [review]
Just realized please change `auto` to a type. Foreigns are a little tricky to work with because you can't perform type inference w/ them - since their type isn't actually known at compile time (or at all really, foreigns aren't supposed to be exposed to the average user, only library developers working with native code).

In this particular case I'd recommend changing the code to: 
```
proc importdll(array<char> lib) return int
  return foreign[19];
```

**Comment by Xanderplayz16** [comment]
Fixed

**Pull request merged**
