### PR TITLE
Time and Beeping

### PR DESCRIPTION
**Pull request by Xanderplayz16**
Can output unix time and make a simple beep.

### CODE REVIEW

**Review by TheRealMichaelWang — CHANGES_REQUESTED** [review]
This isn't valid Cish code. Omitting the { and } only work on functions that consist of *one* statement. `unixtime` has two statements, the set var and return.

Something like this would be more idiomatic with cish:
```
proc unixtime() return int
  return foreign[16];
```
Also note that `return int` must be there because foreign's by default return the `auto` value, so it's type must be specified as `int`.

**Review by TheRealMichaelWang — CHANGES_REQUESTED** [review]
Character literals must be encapsulated by `'` - much like parentheticals in English.

I suggest you change the following function to:
```
proc beep()
  foreign[8]('\a');
```
to be more idiomatic and syntactically correct.

**Comment by TheRealMichaelWang** [comment]
In the future, I'd recommend any changes to the standard library to be run through Cish or Capote first.

**Comment by Xanderplayz16** [comment]
Oh ok.

**Review by Xanderplayz16 — COMMENTED** [review]
Seems good

**Comment by TheRealMichaelWang** [comment]
Hold up I still think we can merge the pull request after some changes are made.

Just apply the changes I recommended:
```
proc unixtime() return int
  return foreign[16];
```
and
```
proc beep()
  foreign[8]('\a');
```

**Comment by Xanderplayz16** [comment]
Just applied the changes, going to open a new pull

**Pull request closed without merging**
